### PR TITLE
Consistent editing UI

### PR DESCRIPTION
**Pull request by sandreae**
image
image

- [x] editable widgets on sightings screen
- [x] editable widgets on species screen

### CODE REVIEW

**Comment by adzialocha** [comment]
How about using an x-Icon or something instead of the lock? I know I've proposed that initially but seeing it now im not sure anymore.

Also clicking the button is like cancelling?

**Comment by sandreae** [comment]
> How about using an x-Icon (Close etc.) or something instead of the lock? I know I've proposed that initially but seeing it now I'm not sure anymore.

Yeh, I also think the locks don't work so well. Will try some alternatives.

> Also clicking the button is like cancelling?

Yep

**Comment by adzialocha** [comment]
This is so much better! Thank you!!

I've noticed some more inconsistencies / confusions but I don't know if they are related to this PR or should be tackled later:

1. When editing "Species" in the "Species Profile Screen", the current value is not displayed, it's just a blank field
2. When editing "Species" in the "Sightings Profile Screen", the text field is automatically selected, in all other widgets we don't do that anymore

**Review by adzialocha — APPROVED** [review]

**Comment by sandreae** [comment]
> 2. When editing "Species" in the "Sightings Profile Screen", the text field is automatically selected, in all other widgets we don't do that anymore

I don't see this behaviour @adzialocha, did you mean in "local name" field?

**Comment by sandreae** [comment]
> > 2. When editing "Species" in the "Sightings Profile Screen", the text field is automatically selected, in all other widgets we don't do that anymore
> 
> I don't see this behaviour @adzialocha, did you mean in "local name" field?

I think this is better to take in another issue anyway, it wasn't introduced in this PR.

**Comment by sandreae** [comment]
> 1. When editing "Species" in the "Species Profile Screen", the current value is not displayed, it's just a blank field

This is fixed though :+1:

**Review by adzialocha — APPROVED** [review]

**Pull request merged**
